name: Tests
on:
  pull_request:
    branches:
      - main
env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/quotes
  VITE_API_URL: http://localhost:3000
  API_SECRET: secretvalue
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PLAYWRIGHT_BROWSERS_PATH: 0
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test:backend:unit
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: ./.github/actions/docker-compose
      - name: Run tests
        run: pnpm run test:backend:int
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: ./.github/actions/docker-compose
      - name: Install Playwright
        run: cd e2e && npx playwright install --with-deps
      - run: cd e2e && npx playwright install
      - name: Run tests
        run: pnpm test:e2e
